# Returns IPv6 dhcp duid.
# If $duid is not 'auto',  return duid
# If $duid is 'auto' and $mac_address is valid MAC address
#   return autogenerated duid
# Else Fail
# Parametres:
#   $duid = $connection duid
function networkmanager::get_ipv6_duid(
  Variant[
      Pattern[/\h{2}(:\h{2})+$/],
      Undef,
      Enum[
          'auto',
          'lease',
          'll',
          'llt',
          'stable-ll',
          'stable-llt',
          'stable-uuid'
        ]
    ] $duid,
  Optional[Stdlib::MAC] $mac_address,
) >> Variant[
  Pattern[/\h{2}(:\h{2})+$/],
  Undef,
  Enum[
    'lease',
    'll',
    'llt',
    'stable-ll',
    'stable-llt',
    'stable-uuid'
  ]
]{
  if 'auto' == $duid {
    if $mac_address {
      networkmanager::connection_duid($mac_address)
    }
    else {
      fail('IPv6 DHCP duid is set to "auto" but the supplied mac addres is invalid!')
    }
  }
  else {
    $duid
  }
}
